import os

SECRET_KEY = "secretkey"
ALGORITHM = "HS256"
ACCESS_TOKEN_EXPIRE_MINUTES = 999999
REFRESH_TOKEN_EXPIRE_DAYS = 7

BASE_URL = os.environ.get("BASE_URL")
OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY")
YASHA_POGODA_KEY = os.environ.get("YASHA_POGODA_KEY")