"""empty message

Revision ID: 79233f0b8e99
Revises: a6ec51643359
Create Date: 2024-10-25 19:47:22.206543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79233f0b8e99'
down_revision: Union[str, None] = 'a6ec51643359'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('achievements', 'picture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('achievements', sa.Column('picture', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
